### ISSUE TITLE
Azure azuread-oauth2 backend access_token problem

### ISSUE THREAD

**Issue by kagenami** [python-social-auth/social-app-django#297] opened 2021-02-05 18:08 UTC
When trying to retrieve an access token for a user logged in using the azuread-oauth2 backend the value we are getting back for the access_token via extra_data does not seem to be a valid access token for querying the Microsoft Graph API.

What we get back when attempting to leverage the access token is a CompactToken parsing error.

Our SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE is set to https://graph.microsoft.com/. 

As per the docs we have encountered everything should be working, but as I said, the access token appears to be wrong.

Any help would be appreciated.

**Comment by nijel** [comment] 2021-02-05 19:02
Duplicate of https://github.com/python-social-auth/social-core/issues/561

**Closed by nijel** 2021-02-05 19:02 UTC
