### ISSUE TITLE
Reauth Gitlab doesn't work

### ISSUE THREAD

**Issue by Spanish93** [python-social-auth/social-app-django#591] opened 2024-07-09 20:17 UTC
Since Defect Dojo use last version of social app Django, reauth with gitlab don't work.
See : https://github.com/DefectDojo/django-DefectDojo/issues/10171

May be related with : https://github.com/python-social-auth/social-app-django/issues/568

**Comment by Spanish93** [comment] 2024-07-10 03:23
Like it's reported here :
https://github.com/python-social-auth/social-app-django/issues/571

Version 5.4.1, don't work with latest social core, and Defect Dojo don't want to downgrade to 5.4.0

**Comment by nijel** [comment] 2024-07-10 06:54
Duplicate of https://github.com/python-social-auth/social-core/issues/924

**Closed by nijel** 2024-07-10 06:54 UTC
