### ISSUE TITLE
Migrations failure

### ISSUE THREAD

**Issue by timbloeme** [python-social-auth/social-app-django#9] opened 2016-12-30 13:49 UTC
When applying the migrations from the new django specific app the following error is thrown.

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/db/migrations/loader.py", line 308, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/db/migrations/loader.py", line 301, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/tim/.virtualenvs/api-kk/lib/python3.5/site-packages/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration social_django.0004_auto_20160423_0400 dependencies reference nonexistent parent node ('social_django', '0003_alter_email_max_length')
```

**Comment by omab** [comment] 2016-12-31 21:57
I can't seem to reproduce this, do you have any extra details?

**Comment by koniiiik** [comment] 2017-01-07 22:27
I could reproduce the same error with a pre-existing database from before the reorganization, where migrations 0001 ­– 0004 were applied with `default` as the appname.

After running `update django_migrations set app='social_django' where app='default';` in a `dbshell`, `showmigrations` is capable of finishing successfully, but it still shows all `social_django` migrations as not applied (even though the first four are already applied). In this state, obviously, running `migrate` leads to an error, because it tries to apply all of them from the beginning, but the tables are already there.

The solution (in my situation) is to run `migrate --fake social_django 0004`, which adds entries to `django_migrations` for all already-applied migrations for appnames `default` and `social_auth` as well. So in the end, I have entries in the `django_migrations` table for all of the already-applied migrations for all three appnames: `default`, `social_auth`, and `social_django`. At this point migrations work correctly for me again.

I did some more digging, and it looks like the problem here is that the `replaces` attribute of a Django migration has a different meaning than what is assumed in the `social_django` package. This does not appear to be documented (or at least, I didn't find it in the docs), but https://github.com/django/django/blob/f582db1296cc18e2ff49846c9be4ad999759adcc/django/db/migrations/migration.py#L39-L42 sheds a little bit of light on the problem.

In short, the way `replaces` is used in this package seems to be along the lines of “Consider this migration applied if any of these two original migrations has been applied before,” whereas the actual meaning as understood by Django is “This migration is a replacement for the entire sequence of these two original migrations.” So, if Django only sees one of the original migrations being applied, but not the other one, it assumes the replacement is not yet applied either. And conversely, when the replacement is being applied, all of the originals get recorded, too, because there might be some other migrations elsewhere that depend on some of the originals. Which also means that if any of the original migrations is missing in the database, the replacement cannot be considered applied either.

Not sure what the way forward would be, though. I guess removing one of the two entries in `replaces` in all migrations would be necessary, and also documenting that a manual `migrate --fake` will be required in certain situations. As far as I understand, Django does not provide any more straight-forward automatic upgrade path for situations like this (but I may be wrong).

**Comment by black3r** [comment] 2017-01-08 20:16
considering the definition of `replaces` attribute the real issue seems to be with the 5th migration having `('default', '0005_auto_20160727_2333'),` in `replaces` because that migration didn't exist while the migrations were applied with appname `default`. 

When migrating my application from 0.2.21 to the new social app structure, no errors were thrown when running `python manage.py migrate`, but the 5th migration for `social_django` remains "unapplied" (there is no record for it in `django_migrations` table), and trying to install it manually by running `python manage.py migrate social_django 0005` results in an error saying: `django.db.migrations.exceptions.NodeNotFoundError: Node ('social_django', '0005_auto_20160727_2333') not a valid node`

The issues with applying migrations 0001-0004 can be resolved with updating to 0.2.21 before updating to the version after the second application rename. 

(My production databases using python social auth version 0.2.21 contain `default` migrations 0001-0004 and `social_auth` migrations 0001-0005)

**Comment by anzellai** [comment] 2017-01-24 14:09
I'm having the same trouble migrating from PSA 0.3.3.
I actually downgraded to 0.2.21 (as with what @black3r suggested above) and applied the migrations `0001` - `0004`, then I have to bypass/comment out the `replaces` migrations to upgrade to current "social_core" & "social_django".

**Comment by roosmaa** [comment] 2017-01-25 11:48
Hit the same snag. Guess I upgraded to new structure too early. For me the problem was the non-existing default 0005 migration. Fixed by doing:

```
$ python manage.py dbshell
=> INSERT INTO django_migrations(app, name, applied) VALUES('default', '0005_auto_20160727_2333', NOW());
```

After that the migrate command ran successfully.

**Comment by nijel** [comment] 2017-01-27 11:33
Should be fixed by https://github.com/python-social-auth/social-app-django/pull/25

**Comment by omab** [comment] 2017-01-28 14:08
Closing since #25 is merged, reopen if needed. Thanks @nijel.

**Closed by omab** 2017-01-28 14:08 UTC
